"""Curated demo documents for FOLIO Enrich one-click demo exemplars.

Each document is purpose-built to exercise specific pipeline features.
"""

DEMO_DOCUMENTS: dict[str, dict] = {
    "litigation": {
        "title": "Litigation",
        "description": "Motion to dismiss with rich citations, Rule 12(b)(6), multi-branch negligence/contract concepts",
        "text": (
            "UNITED STATES DISTRICT COURT\n"
            "NORTHERN DISTRICT OF CALIFORNIA\n\n"
            "SILVERSTONE CAPITAL PARTNERS, LLC,\n"
            "  Plaintiff,\n\n"
            "v.\n\n"
            "NEXTERA TECHNOLOGIES, INC., and JOHN MORRISON, individually,\n"
            "  Defendants.\n\n"
            "Case No. 3:24-cv-01592-RJB\n\n"
            "DEFENDANTS' MOTION TO DISMISS PURSUANT TO FEDERAL RULE OF CIVIL PROCEDURE 12(b)(6)\n\n"
            "TO THE HONORABLE JUDGE RACHEL J. BRENNAN:\n\n"
            "Defendants NexTera Technologies, Inc. and John Morrison (collectively, \"Defendants\") "
            "respectfully move this Court for an order dismissing all claims asserted in Plaintiff "
            "Silverstone Capital Partners, LLC's Complaint pursuant to Federal Rule of Civil Procedure "
            "12(b)(6) for failure to state a claim upon which relief can be granted.\n\n"
            "I. INTRODUCTION\n\n"
            "Plaintiff's Complaint alleges breach of contract, negligence, fraudulent misrepresentation, "
            "and unjust enrichment arising from a failed software licensing agreement executed on "
            "June 15, 2023. The total damages claimed are $4,750,000.00. For the reasons set forth "
            "below, each claim fails as a matter of law.\n\n"
            "II. FACTUAL BACKGROUND\n\n"
            "On June 15, 2023, Silverstone Capital Partners, LLC entered into a Master Software License "
            "Agreement (the \"Agreement\") with NexTera Technologies, Inc. for the deployment of NexTera's "
            "proprietary artificial intelligence platform, \"Cortex AI,\" at Silverstone's offices at "
            "1200 Market Street, Suite 400, San Francisco, California 94102.\n\n"
            "The Agreement required NexTera to deliver the Cortex AI platform by September 30, 2023, "
            "with full integration into Silverstone's existing portfolio management system. The total "
            "contract price was $2,500,000.00, payable in three installments.\n\n"
            "Silverstone paid the first installment of $750,000.00 on July 1, 2023, and the second "
            "installment of $750,000.00 on August 15, 2023, for a total of $1,500,000.00 paid to date. "
            "NexTera delivered a beta version of Cortex AI on September 28, 2023.\n\n"
            "III. LEGAL STANDARD\n\n"
            "Under Rule 12(b)(6), a complaint must be dismissed if it fails to state a claim upon which "
            "relief can be granted. Bell Atlantic Corp. v. Twombly, 550 U.S. 544, 570 (2007). To survive "
            "a motion to dismiss, a complaint must contain sufficient factual matter, accepted as true, "
            "to state a claim to relief that is plausible on its face. Ashcroft v. Iqbal, 556 U.S. 662, "
            "678 (2009). A claim has facial plausibility when the plaintiff pleads factual content that "
            "allows the court to draw the reasonable inference that the defendant is liable for the "
            "misconduct alleged. Id.\n\n"
            "IV. ARGUMENT\n\n"
            "A. The Breach of Contract Claim Fails Because the Agreement's Limitation of Liability "
            "Clause Bars the Damages Sought\n\n"
            "Section 9.2 of the Agreement provides that \"in no event shall either party's aggregate "
            "liability under this Agreement exceed the total fees actually paid.\" Silverstone seeks "
            "$4,750,000.00 in damages, which exceeds the $1,500,000.00 in fees paid. Courts routinely "
            "enforce limitation of liability clauses in commercial contracts between sophisticated "
            "parties. See Snibbe v. Superior Court, 224 Cal. App. 4th 184, 190 (2014); Applied "
            "Elastomerics, Inc. v. Z-Man Fishing Products, Inc., 521 F.3d 1156 (9th Cir. 2008).\n\n"
            "B. The Negligence Claim Is Barred by the Economic Loss Rule\n\n"
            "California's economic loss rule provides that purely economic losses are not recoverable "
            "in tort when they arise from a contractual relationship. Robinson Helicopter Co., Inc. v. "
            "Dana Corp., 34 Cal. 4th 979, 988 (2004). Silverstone's negligence claim seeks the same "
            "economic damages that flow from the alleged breach of the Agreement. Because no independent "
            "duty exists outside the contract, the negligence claim is barred. Aas v. Superior Court, "
            "24 Cal. 4th 627, 636 (2000).\n\n"
            "C. The Fraudulent Misrepresentation Claim Fails to Satisfy Rule 9(b)\n\n"
            "Federal Rule of Civil Procedure 9(b) requires that fraud claims be stated with "
            "particularity. Kearns v. Ford Motor Co., 567 F.3d 1120, 1124 (9th Cir. 2009). Silverstone's "
            "Complaint fails to identify the specific statements allegedly made, who made them, when "
            "they were made, or why they were false at the time they were made. This falls far short "
            "of the heightened pleading standard.\n\n"
            "D. The Unjust Enrichment Claim Is Duplicative\n\n"
            "Where a valid and enforceable contract governs the subject matter, an unjust enrichment "
            "claim cannot stand. Paracor Finance, Inc. v. General Electric Capital Corp., 96 F.3d 1151, "
            "1167 (9th Cir. 1996). Because the parties' rights and obligations are governed by the "
            "Agreement, the unjust enrichment claim should be dismissed.\n\n"
            "V. CONCLUSION\n\n"
            "For the foregoing reasons, Defendants respectfully request that this Court grant their "
            "motion and dismiss Plaintiff's Complaint in its entirety with prejudice.\n\n"
            "Dated: March 15, 2024\n\n"
            "Respectfully submitted,\n\n"
            "HARRISON & WEBB LLP\n\n"
            "/s/ Catherine R. Nakamura\n"
            "Catherine R. Nakamura (SBN 287451)\n"
            "cnakamura@harrisonwebb.com\n"
            "600 Montgomery Street, Suite 2200\n"
            "San Francisco, CA 94111\n"
            "Telephone: (415) 555-0142\n"
            "Attorneys for Defendants"
        ),
    },
    "transactional": {
        "title": "Transactional",
        "description": "Asset purchase agreement with corporate entities, IP provisions, and complex contract terms",
        "text": (
            "ASSET PURCHASE AGREEMENT\n\n"
            "This Asset Purchase Agreement (this \"Agreement\") is entered into as of March 1, 2024, by "
            "and between:\n\n"
            "BUYER: Apex Dynamics Holdings, Inc., a Delaware corporation, with its principal place of "
            "business at 2400 Sand Hill Road, Suite 300, Menlo Park, California 94025 (\"Buyer\"); and\n\n"
            "SELLER: Quantum Logic Systems, LLC, a Nevada limited liability company, with its principal "
            "place of business at 8900 Technology Drive, Reno, Nevada 89521 (\"Seller\").\n\n"
            "RECITALS\n\n"
            "WHEREAS, Seller is engaged in the business of developing and licensing enterprise data "
            "analytics software, including its flagship product known as \"DataStream Pro\" "
            "(the \"Business\"); and\n\n"
            "WHEREAS, Buyer desires to purchase and Seller desires to sell substantially all of the "
            "assets of the Business on the terms and conditions set forth herein;\n\n"
            "NOW, THEREFORE, in consideration of the mutual covenants and agreements hereinafter set "
            "forth and for other good and valuable consideration, the receipt and sufficiency of which "
            "are hereby acknowledged, the parties agree as follows:\n\n"
            "ARTICLE I — PURCHASE AND SALE OF ASSETS\n\n"
            "1.1 Purchased Assets. Subject to the terms and conditions of this Agreement, at the "
            "Closing, Seller shall sell, transfer, assign, convey, and deliver to Buyer, and Buyer "
            "shall purchase and accept from Seller, all right, title, and interest in and to the "
            "following assets (collectively, the \"Purchased Assets\"):\n\n"
            "(a) Intellectual Property. All patents, patent applications, copyrights, trademarks, trade "
            "names, service marks, trade secrets, know-how, and other intellectual property rights "
            "related to the Business, including without limitation:\n"
            "  (i) U.S. Patent No. 11,234,567 — \"Method for Real-Time Streaming Data Aggregation\"\n"
            "  (ii) U.S. Patent Application No. 17/890,123 — \"Machine Learning Pipeline Optimization\"\n"
            "  (iii) The \"DataStream Pro\" trademark, Registration No. 6,789,012\n"
            "  (iv) All source code, object code, documentation, and related materials for the "
            "DataStream Pro platform\n\n"
            "(b) Customer Contracts. All customer license agreements, maintenance agreements, and "
            "subscription agreements listed on Schedule 1.1(b), including the enterprise license "
            "agreement with Morgan Stanley & Co. LLC dated January 10, 2023.\n\n"
            "(c) Tangible Personal Property. All computer equipment, servers, networking equipment, "
            "and office furniture located at Seller's Reno facility, as listed on Schedule 1.1(c).\n\n"
            "1.2 Excluded Assets. The following assets are expressly excluded from the Purchased Assets: "
            "(a) cash and cash equivalents; (b) Seller's organizational documents; (c) all rights "
            "under this Agreement; (d) the name \"Quantum Logic Systems.\"\n\n"
            "ARTICLE II — PURCHASE PRICE\n\n"
            "2.1 Purchase Price. The aggregate purchase price for the Purchased Assets shall be "
            "Forty-Five Million Dollars ($45,000,000.00) (the \"Purchase Price\"), payable as follows:\n\n"
            "(a) Cash at Closing: $35,000,000.00 by wire transfer of immediately available funds;\n"
            "(b) Escrow Deposit: $5,000,000.00 deposited with Wells Fargo Bank, N.A., as escrow agent; "
            "and\n"
            "(c) Promissory Note: $5,000,000.00 payable over 24 months pursuant to the Seller Note.\n\n"
            "ARTICLE III — REPRESENTATIONS AND WARRANTIES OF SELLER\n\n"
            "Seller represents and warrants to Buyer as follows:\n\n"
            "3.1 Organization. Seller is a limited liability company duly organized, validly existing, "
            "and in good standing under the laws of the State of Nevada.\n\n"
            "3.2 Intellectual Property. Seller owns or has valid licenses to all Intellectual Property "
            "used in the Business. To Seller's knowledge, none of the Intellectual Property infringes "
            "upon the rights of any third party. There are no pending or threatened claims of "
            "infringement against Seller.\n\n"
            "3.3 Compliance with Laws. Seller is in material compliance with all applicable federal, "
            "state, and local laws, including data privacy regulations such as the California Consumer "
            "Privacy Act (CCPA) and the General Data Protection Regulation (GDPR).\n\n"
            "ARTICLE IV — INDEMNIFICATION\n\n"
            "4.1 Indemnification by Seller. Seller shall indemnify and hold harmless Buyer from any "
            "losses arising from breaches of Seller's representations and warranties. The total "
            "indemnification obligation shall not exceed $10,000,000.00.\n\n"
            "4.2 Survival. The representations and warranties shall survive the Closing for a period "
            "of eighteen (18) months, except that the representations in Sections 3.1 and 3.2 shall "
            "survive for thirty-six (36) months.\n\n"
            "ARTICLE V — CLOSING\n\n"
            "5.1 Closing Date. The closing of the transactions contemplated by this Agreement "
            "(the \"Closing\") shall take place on April 15, 2024, at the offices of Baker McKenzie LLP, "
            "300 East Randolph Street, Suite 5000, Chicago, Illinois 60601.\n\n"
            "IN WITNESS WHEREOF, the parties have executed this Agreement as of the date first written "
            "above.\n\n"
            "APEX DYNAMICS HOLDINGS, INC.\n"
            "By: /s/ Marcus T. Williams\n"
            "Name: Marcus T. Williams\n"
            "Title: Chief Executive Officer\n\n"
            "QUANTUM LOGIC SYSTEMS, LLC\n"
            "By: /s/ Elena V. Petrov\n"
            "Name: Elena V. Petrov\n"
            "Title: Managing Member"
        ),
    },
    "advisory": {
        "title": "Advisory",
        "description": "Legal memorandum with multi-area risk analysis spanning employment, IP, and regulatory law",
        "text": (
            "WHITFIELD & ASSOCIATES LLP\n"
            "ATTORNEYS AT LAW\n\n"
            "MEMORANDUM\n\n"
            "PRIVILEGED AND CONFIDENTIAL\n"
            "ATTORNEY-CLIENT COMMUNICATION\n\n"
            "TO:        Sarah Kimura, General Counsel\n"
            "           Cascade Biotech, Inc.\n\n"
            "FROM:      Robert L. Whitfield\n"
            "           Jennifer A. Park\n\n"
            "DATE:      March 10, 2024\n\n"
            "RE:        Regulatory and Litigation Risk Assessment — Proposed Acquisition of "
            "GeneStar Therapeutics, Inc.\n\n"
            "I. EXECUTIVE SUMMARY\n\n"
            "You have asked us to assess the legal risks associated with Cascade Biotech's proposed "
            "acquisition of GeneStar Therapeutics, Inc., a clinical-stage biotechnology company focused "
            "on CRISPR-based gene therapies. Our analysis identifies risks across five legal domains: "
            "(1) intellectual property, (2) FDA regulatory compliance, (3) employment and non-compete "
            "agreements, (4) data privacy and security, and (5) antitrust considerations.\n\n"
            "Our overall risk rating is MODERATE-HIGH. While the target's IP portfolio is strong, "
            "pending FDA inspections and unresolved employment disputes create material uncertainties "
            "that could affect the $280,000,000.00 valuation.\n\n"
            "II. INTELLECTUAL PROPERTY RISK ASSESSMENT\n\n"
            "A. Patent Portfolio\n\n"
            "GeneStar holds 14 issued U.S. patents and 8 pending patent applications covering its "
            "CRISPR delivery mechanisms and guide RNA sequences. The key asset is U.S. Patent No. "
            "11,456,789, covering a novel lipid nanoparticle delivery system for CRISPR-Cas9 payloads.\n\n"
            "However, we identified that the Broad Institute of MIT and Harvard holds a potentially "
            "overlapping patent (U.S. Patent No. 10,987,654) covering similar lipid nanoparticle "
            "compositions. An interference proceeding or invalidity challenge is possible. We recommend "
            "engaging a patent prosecution firm to conduct a freedom-to-operate analysis before closing.\n\n"
            "B. Trade Secrets\n\n"
            "GeneStar's manufacturing process for its lead candidate, GS-201, constitutes valuable "
            "trade secret information protected under the Defend Trade Secrets Act, 18 U.S.C. "
            "\u00A7\u00A7 1831-1839, and the California Uniform Trade Secrets Act, Cal. Civ. Code "
            "\u00A7\u00A7 3426-3426.11. Adequate confidentiality protections are essential during "
            "the due diligence process.\n\n"
            "III. FDA REGULATORY COMPLIANCE\n\n"
            "GeneStar's lead product candidate, GS-201, is currently in Phase II clinical trials "
            "under IND Application No. 123456. The FDA's Center for Biologics Evaluation and Research "
            "(CBER) issued a clinical hold on February 1, 2024, citing concerns about observed "
            "off-target editing effects in three study participants.\n\n"
            "Resolution of the clinical hold requires submission of amended protocols and additional "
            "safety data, which GeneStar estimates will take 4-6 months. During this period, enrollment "
            "is suspended, and the timeline for a Biologics License Application (BLA) submission is "
            "uncertain.\n\n"
            "We also note that GeneStar received a Form FDA 483 during a January 2024 inspection of "
            "its manufacturing facility in San Diego, California, citing three observations related to "
            "current Good Manufacturing Practice (cGMP) compliance.\n\n"
            "IV. EMPLOYMENT AND NON-COMPETE ISSUES\n\n"
            "Three key GeneStar scientists — Dr. Li Wei, Dr. Priya Sharma, and Dr. James Okafor — "
            "previously worked at CRISPR Therapeutics AG and are subject to non-competition and "
            "non-solicitation agreements. CRISPR Therapeutics sent a cease-and-desist letter on "
            "December 15, 2023, alleging that Dr. Wei's work at GeneStar violates his non-compete.\n\n"
            "Under California Business and Professions Code \u00A7 16600, non-compete agreements are "
            "generally unenforceable. However, Dr. Wei performed some work in Massachusetts, where "
            "such agreements may be enforceable under the Massachusetts Noncompetition Agreement Act, "
            "Mass. Gen. Laws ch. 149, \u00A7 24L. The choice-of-law question creates litigation risk.\n\n"
            "V. DATA PRIVACY AND SECURITY\n\n"
            "GeneStar collects genetic data from clinical trial participants, which constitutes "
            "Protected Health Information under HIPAA, 42 U.S.C. \u00A7\u00A7 1320d-1320d-9, and "
            "sensitive personal information under the CCPA. GeneStar's privacy policy has not been "
            "updated since 2021 and does not address the requirements of the California Privacy Rights "
            "Act (CPRA), which took effect on January 1, 2023.\n\n"
            "Additionally, genetic information is subject to the Genetic Information Nondiscrimination "
            "Act (GINA), 42 U.S.C. \u00A7\u00A7 2000ff et seq., which restricts the use of genetic "
            "information in employment and health insurance contexts.\n\n"
            "VI. ANTITRUST CONSIDERATIONS\n\n"
            "The proposed acquisition may require a Hart-Scott-Rodino (HSR) premerger notification "
            "filing with the Federal Trade Commission and the Department of Justice Antitrust Division. "
            "The current HSR filing threshold is $111.4 million, and the $280,000,000.00 transaction "
            "value exceeds this threshold. The waiting period is typically 30 days.\n\n"
            "VII. RECOMMENDATIONS\n\n"
            "1. Conduct a freedom-to-operate patent analysis before closing.\n"
            "2. Require GeneStar to resolve the FDA clinical hold as a condition precedent.\n"
            "3. Obtain representations and warranties insurance covering the employment disputes.\n"
            "4. Engage a privacy consultant to audit GeneStar's HIPAA and CCPA compliance.\n"
            "5. File the HSR notification immediately to avoid delays.\n\n"
            "Please contact us to discuss these findings at your convenience.\n\n"
            "Respectfully submitted,\n\n"
            "Robert L. Whitfield\n"
            "Jennifer A. Park\n"
            "WHITFIELD & ASSOCIATES LLP\n"
            "500 Sansome Street, Suite 1500\n"
            "San Francisco, CA 94111\n"
            "Telephone: (415) 555-0298"
        ),
    },
    "regulatory": {
        "title": "Regulatory",
        "description": "Federal agency enforcement action with government bodies, compliance terms, and regulatory frameworks",
        "text": (
            "UNITED STATES SECURITIES AND EXCHANGE COMMISSION\n\n"
            "In the Matter of:\n"
            "MERIDIAN FINANCIAL SERVICES, INC.\n\n"
            "Administrative Proceeding File No. 3-21456\n\n"
            "ORDER INSTITUTING CEASE-AND-DESIST PROCEEDINGS PURSUANT TO SECTION 8A OF THE "
            "SECURITIES ACT OF 1933 AND SECTION 21C OF THE SECURITIES EXCHANGE ACT OF 1934\n\n"
            "I. SUMMARY\n\n"
            "The Securities and Exchange Commission (\"Commission\") deems it appropriate that "
            "cease-and-desist proceedings be instituted against Meridian Financial Services, Inc. "
            "(\"Meridian\" or \"Respondent\") pursuant to Section 8A of the Securities Act of 1933 "
            "(\"Securities Act\") and Section 21C of the Securities Exchange Act of 1934 "
            "(\"Exchange Act\").\n\n"
            "II. RESPONDENT\n\n"
            "Meridian Financial Services, Inc. is a Delaware corporation with its principal offices "
            "at 400 Park Avenue, New York, New York 10022. Meridian is registered with the Commission "
            "as a broker-dealer pursuant to Section 15(b) of the Exchange Act and is a member of the "
            "Financial Industry Regulatory Authority (\"FINRA\"). During the relevant period, Meridian "
            "employed approximately 450 registered representatives.\n\n"
            "III. FACTS\n\n"
            "A. Background\n\n"
            "From January 2022 through December 2023 (the \"Relevant Period\"), Meridian failed to "
            "establish, maintain, and enforce adequate supervisory systems and written supervisory "
            "procedures to prevent and detect unsuitable recommendations by its registered "
            "representatives.\n\n"
            "B. Regulation Best Interest Violations\n\n"
            "The Commission's Office of Compliance Inspections and Examinations (\"OCIE\") conducted "
            "an examination of Meridian from March through June 2023. The examination revealed that "
            "Meridian's registered representatives recommended complex products — including leveraged "
            "and inverse exchange-traded funds, structured notes, and private placement offerings — "
            "to retail customers without a reasonable basis to believe that these products were in the "
            "customers' best interest, as required by Regulation Best Interest, 17 C.F.R. \u00A7 240.15l-1.\n\n"
            "Specifically:\n\n"
            "(1) In 147 customer accounts, registered representatives recommended leveraged ETFs "
            "for long-term hold periods exceeding 30 days, contrary to the products' stated investment "
            "objectives and the guidance in FINRA Regulatory Notice 09-31.\n\n"
            "(2) In 83 accounts, representatives failed to disclose material conflicts of interest, "
            "including revenue-sharing arrangements with product sponsors that paid Meridian an "
            "additional 25 basis points for each sale.\n\n"
            "(3) Meridian's Customer Relationship Summary (Form CRS), required by Form CRS Rule "
            "17 C.F.R. \u00A7 240.17a-14, contained materially misleading statements about the nature "
            "and scope of its brokerage services.\n\n"
            "C. Anti-Money Laundering Deficiencies\n\n"
            "The examination also identified significant deficiencies in Meridian's Bank Secrecy Act "
            "(\"BSA\") and anti-money laundering (\"AML\") compliance program, as required by "
            "31 C.F.R. \u00A7 1023.210. Meridian failed to file timely Suspicious Activity Reports "
            "(\"SARs\") in 23 instances where transactions exhibited indicia of potential money "
            "laundering or suspicious activity, including:\n\n"
            "- Wire transfers totaling $12,400,000.00 to and from accounts at foreign financial "
            "institutions in jurisdictions identified by the Financial Action Task Force (\"FATF\") "
            "as having strategic deficiencies;\n"
            "- Structuring of cash deposits in amounts just below the $10,000.00 Currency Transaction "
            "Report threshold;\n"
            "- Rapid movement of funds through multiple accounts with no apparent business purpose.\n\n"
            "Meridian's Chief Compliance Officer acknowledged in a memorandum dated August 15, 2023, "
            "that the firm's AML monitoring system had not been updated since 2019 and did not "
            "incorporate current FinCEN Advisory FIN-2022-A001.\n\n"
            "IV. VIOLATIONS\n\n"
            "Based on the foregoing, the Commission finds that Meridian violated:\n\n"
            "(a) Section 17(a)(2) of the Securities Act, which prohibits obtaining money or property "
            "by means of material misstatements or omissions;\n"
            "(b) Section 15(c)(3) of the Exchange Act and Rule 15c3-5 thereunder;\n"
            "(c) Regulation Best Interest, 17 C.F.R. \u00A7 240.15l-1;\n"
            "(d) Exchange Act Section 17(a) and Rule 17a-8 thereunder, requiring BSA/AML compliance.\n\n"
            "V. SANCTIONS\n\n"
            "In view of the foregoing, the Commission deems it appropriate to impose the following "
            "sanctions:\n\n"
            "1. Meridian shall cease and desist from committing or causing any violations of the "
            "above provisions;\n"
            "2. Meridian shall pay a civil monetary penalty of $8,500,000.00;\n"
            "3. Meridian shall pay disgorgement of $3,200,000.00 plus prejudgment interest of "
            "$340,000.00;\n"
            "4. Meridian shall retain an independent compliance consultant approved by the Commission;\n"
            "5. Meridian shall submit quarterly compliance reports to the Commission for a period of "
            "two years.\n\n"
            "By the Commission.\n\n"
            "Vanessa A. Countryman\n"
            "Secretary\n"
            "March 5, 2024"
        ),
    },
    "timekeeping": {
        "title": "Timekeeping",
        "description": "Billing narrative entries with short event-driven descriptions and time verbs",
        "text": (
            "KIRKLAND & ELLIS LLP\n"
            "BILLING NARRATIVE — CLIENT MATTER 4892-001\n"
            "CLIENT: Westbrook Industries, Inc. v. Pacific Rim Supply Chain, LLC\n"
            "PERIOD: March 1-15, 2024\n\n"
            "DATE       TIMEKEEPER            HOURS  DESCRIPTION\n"
            "03/01/24   M. Chen (Partner)      2.40  Reviewed and analyzed plaintiff's first set "
            "of interrogatories; drafted preliminary responses to interrogatories 1-15; conferred "
            "with associate regarding document production timeline.\n\n"
            "03/01/24   A. Singh (Associate)    3.70  Researched California law on trade secret "
            "misappropriation under the Uniform Trade Secrets Act; drafted memorandum analyzing "
            "elements of misappropriation claim; reviewed Silvaco Data Systems v. Intel Corp., "
            "184 Cal. App. 4th 210 (2010).\n\n"
            "03/02/24   M. Chen (Partner)      1.50  Conferred with client regarding settlement "
            "demand of $3,500,000.00; discussed litigation strategy and potential counterclaim for "
            "breach of the Mutual Non-Disclosure Agreement dated January 5, 2023.\n\n"
            "03/03/24   A. Singh (Associate)    4.20  Drafted motion for protective order regarding "
            "confidential business information; researched good cause standard under Federal Rule of "
            "Civil Procedure 26(c); analyzed In re Roman Catholic Archbishop of Portland, "
            "661 F.3d 417 (9th Cir. 2011).\n\n"
            "03/04/24   P. Lawson (Paralegal)   5.80  Organized and indexed 2,347 documents produced "
            "by plaintiff; prepared privilege log for 89 withheld documents; coded documents in "
            "Relativity for attorney review.\n\n"
            "03/05/24   M. Chen (Partner)      0.80  Attended telephonic status conference with "
            "Judge Martinez; obtained extension of discovery deadline to April 30, 2024; reported "
            "conference results to client.\n\n"
            "03/06/24   A. Singh (Associate)    2.90  Prepared deposition outline for plaintiff's "
            "CEO David Park; identified key documents for examination; drafted deposition notices "
            "for three additional witnesses.\n\n"
            "03/07/24   M. Chen (Partner)      1.20  Reviewed and revised protective order motion; "
            "conferred with opposing counsel James Butler of Quinn Emanuel regarding stipulated "
            "protective order; negotiated confidentiality designations.\n\n"
            "03/08/24   A. Singh (Associate)    6.10  Attended and defended deposition of client's "
            "VP of Engineering, Dr. Rachel Okafor; prepared witness for examination; interposed "
            "objections to 14 questions on privilege grounds.\n\n"
            "03/11/24   M. Chen (Partner)      3.50  Reviewed expert report of Dr. Thomas Brennan "
            "regarding damages calculation; analyzed methodology for lost profits computation; "
            "conferred with damages expert regarding rebuttal opinions.\n\n"
            "03/12/24   P. Lawson (Paralegal)   4.30  Filed motion for protective order with the "
            "court; served copies on all parties; calendared response deadline for March 26, 2024; "
            "updated case docket tracking spreadsheet.\n\n"
            "03/13/24   A. Singh (Associate)    3.40  Drafted opposition to plaintiff's motion to "
            "compel production of source code; researched proportionality requirements under "
            "Federal Rule of Civil Procedure 26(b)(1); analyzed Waymo LLC v. Uber Technologies, "
            "Inc., No. 17-cv-00939 (N.D. Cal. 2017).\n\n"
            "03/14/24   M. Chen (Partner)      2.80  Conferred with co-counsel regarding mediation "
            "preparation; drafted mediation brief outlining liability defenses and damages analysis; "
            "reviewed mediator's pre-session questionnaire.\n\n"
            "03/15/24   A. Singh (Associate)    1.60  Finalized privilege log; reviewed and revised "
            "responses to interrogatories; prepared materials for client review and signature.\n\n"
            "SUMMARY\n"
            "Total Partner Hours:      12.20\n"
            "Total Associate Hours:    21.90\n"
            "Total Paralegal Hours:    10.10\n"
            "Total All Timekeepers:    44.20\n"
            "Total Fees (blended):     $36,850.00\n"
            "Total Costs Advanced:     $2,145.00 (filing fees, deposition transcripts, Relativity hosting)"
        ),
    },
    "multi-branch": {
        "title": "Multi-Branch",
        "description": "International dispute exercising 8+ FOLIO branches with stacked gradient borders",
        "text": (
            "IN THE MATTER OF THE ARBITRATION BETWEEN\n\n"
            "STERLING MARITIME CORPORATION, a Liberian corporation,\n"
            "  Claimant,\n\n"
            "AND\n\n"
            "ASIA PACIFIC ENERGY TRADING PTE. LTD., a Singapore company,\n"
            "  Respondent.\n\n"
            "INTERNATIONAL CHAMBER OF COMMERCE\n"
            "Case No. 27893/RJL\n\n"
            "PARTIAL AWARD ON LIABILITY\n\n"
            "I. PROCEDURAL HISTORY\n\n"
            "This arbitration arises under the arbitration clause in the Crude Oil Sale and Purchase "
            "Agreement dated May 15, 2023, between Sterling Maritime Corporation (\"Sterling\") and "
            "Asia Pacific Energy Trading Pte. Ltd. (\"APET\"). The Arbitral Tribunal was constituted "
            "on September 1, 2023, in accordance with the ICC Rules of Arbitration (2021). The seat "
            "of arbitration is London, England. The proceedings are governed by English law.\n\n"
            "The Tribunal held an evidentiary hearing from January 22 to January 26, 2024, at the "
            "International Dispute Resolution Centre, 70 Fleet Street, London EC4Y 1EU. Twelve "
            "witnesses of fact and four expert witnesses testified.\n\n"
            "II. FACTUAL BACKGROUND\n\n"
            "A. The Transaction\n\n"
            "On May 15, 2023, Sterling and APET entered into a Crude Oil Sale and Purchase Agreement "
            "(the \"Agreement\") for the sale of 500,000 barrels of Brent crude oil at a price of "
            "$78.50 per barrel, for a total contract value of $39,250,000.00. Delivery was to occur "
            "FOB at the Port of Rotterdam, Netherlands, on or before July 31, 2023.\n\n"
            "Sterling chartered the vessel M/V Northern Star, a 150,000 deadweight tonnage Suezmax "
            "tanker registered in the Marshall Islands, for the voyage from the Hound Point Terminal, "
            "Scotland, to the Port of Rotterdam.\n\n"
            "B. The Dispute\n\n"
            "On July 15, 2023, the M/V Northern Star suffered a mechanical failure in the North Sea "
            "approximately 200 nautical miles from Rotterdam. The vessel was towed to the Port of "
            "Antwerp, Belgium, where it underwent emergency repairs. The cargo was not delivered until "
            "August 20, 2023 — twenty days late.\n\n"
            "During the delay, the price of Brent crude fell from $78.50 to $72.30 per barrel. APET "
            "claims damages of $3,100,000.00, representing the price differential on 500,000 barrels "
            "plus additional demurrage costs of $450,000.00 and insurance premium increases of "
            "$175,000.00.\n\n"
            "Sterling contends that the mechanical failure constitutes a force majeure event under "
            "Article 12 of the Agreement and that APET failed to mitigate its damages by refusing "
            "to accept substitute cargo available from BP Trading & Shipping Company Limited.\n\n"
            "III. LEGAL ANALYSIS\n\n"
            "A. Force Majeure\n\n"
            "Article 12.1 of the Agreement provides that neither party shall be liable for failure "
            "to perform its obligations if such failure results from circumstances beyond the party's "
            "reasonable control. The Tribunal finds that a mechanical failure attributable to deferred "
            "maintenance does not satisfy the force majeure standard. See Channel Island Ferries Ltd "
            "v. Sealink UK Ltd [1988] 1 Lloyd's Rep 323; Thames Valley Power Ltd v. Total Gas & "
            "Power Ltd [2005] EWHC 2208 (Comm).\n\n"
            "B. Mitigation of Damages\n\n"
            "The Tribunal finds that APET acted reasonably in declining BP's substitute cargo offer, "
            "which was offered at $80.25 per barrel — above the original contract price. The duty to "
            "mitigate does not require a party to accept an unreasonable substitute. See British "
            "Westinghouse Electric v. Underground Electric Railways [1912] AC 673.\n\n"
            "C. Damages Assessment\n\n"
            "The Tribunal awards APET damages of $3,100,000.00 for the price differential, "
            "$450,000.00 for demurrage, and $175,000.00 for insurance costs, for a total award "
            "of $3,725,000.00 plus interest at SOFR plus 2% from August 20, 2023, to the date "
            "of payment.\n\n"
            "IV. COSTS\n\n"
            "The Tribunal orders Sterling to bear the costs of the arbitration, including the "
            "ICC administrative expenses of $125,000.00 and the arbitrators' fees of $380,000.00.\n\n"
            "Made in London, England\n"
            "February 28, 2024\n\n"
            "The Arbitral Tribunal:\n"
            "Lord Justice Michael Pemberton (Presiding Arbitrator)\n"
            "Professor Hiroshi Tanaka\n"
            "Dame Elizabeth Carrington QC"
        ),
    },
    "individuals": {
        "title": "Individuals",
        "description": "Dense with citations, monetary amounts, dates, addresses, named entities",
        "text": (
            "FINAL JUDGMENT AND ORDER OF DISTRIBUTION\n\n"
            "IN THE CIRCUIT COURT OF COOK COUNTY, ILLINOIS\n"
            "PROBATE DIVISION\n\n"
            "In Re: Estate of MARGARET ELEANOR WORTHINGTON, Deceased\n"
            "Case No. 2023-P-004521\n\n"
            "THIS CAUSE came before the Court on the Petition for Final Distribution filed by "
            "First National Bank of Chicago, as Executor of the Estate of Margaret Eleanor "
            "Worthington (\"Decedent\"), who died testate on October 12, 2023, at the age of 87, "
            "at Northwestern Memorial Hospital, 251 East Huron Street, Chicago, Illinois 60611.\n\n"
            "The Court, having reviewed the final accounting, the inventory and appraisal, all "
            "claims filed against the estate, and the objections filed by interested parties, and "
            "being fully advised in the premises, FINDS as follows:\n\n"
            "I. ESTATE ASSETS AND VALUATION\n\n"
            "The total gross estate of the Decedent, as determined by the appraiser, Robert J. "
            "Flanagan, MAI, of Flanagan & Associates, 180 North LaSalle Street, Suite 3200, "
            "Chicago, Illinois 60601, is valued at $14,850,000.00, consisting of:\n\n"
            "(a) Real Property:\n"
            "  - Residence at 1440 North Lake Shore Drive, Unit 32B, Chicago, IL 60610 — $3,200,000.00\n"
            "  - Vacation home at 285 Ocean Road, Kennebunkport, Maine 04046 — $1,750,000.00\n"
            "  - Rental property at 742 West Webster Avenue, Chicago, IL 60614 — $825,000.00\n\n"
            "(b) Financial Assets:\n"
            "  - JPMorgan Chase & Co. investment account ending in 4589 — $4,250,000.00\n"
            "  - Charles Schwab & Co. brokerage account ending in 7823 — $2,100,000.00\n"
            "  - Northern Trust Company trust account — $1,450,000.00\n"
            "  - Bank of America checking account ending in 3012 — $175,000.00\n\n"
            "(c) Personal Property:\n"
            "  - Art collection appraised by Christie's International Real Estate — $850,000.00\n"
            "  - Jewelry appraised by Tiffany & Co. — $250,000.00\n\n"
            "II. DEBTS AND EXPENSES\n\n"
            "The following claims have been allowed:\n"
            "  - Northwestern Memorial Hospital — medical expenses: $287,450.00\n"
            "  - Internal Revenue Service — federal estate tax (Form 706): $2,145,000.00\n"
            "  - Illinois Department of Revenue — state estate tax: $412,000.00\n"
            "  - Executor's fees (First National Bank of Chicago): $148,500.00\n"
            "  - Attorney's fees (Winston & Strawn LLP): $95,000.00\n"
            "  - Accounting fees (Deloitte & Touche LLP): $45,000.00\n"
            "  - Funeral and burial expenses: $22,500.00\n"
            "Total debts and expenses: $3,155,450.00\n\n"
            "III. NET DISTRIBUTABLE ESTATE\n\n"
            "The net distributable estate, after payment of all allowed claims and expenses, "
            "is $11,694,550.00.\n\n"
            "IV. DISTRIBUTION\n\n"
            "Pursuant to the Last Will and Testament of Margaret Eleanor Worthington, executed "
            "on June 3, 2019, and admitted to probate on November 15, 2023, the estate shall be "
            "distributed as follows:\n\n"
            "(a) To ELIZABETH ANNE WORTHINGTON PRICE, daughter, of 890 Park Avenue, New York, "
            "NY 10075 — 40% of the net estate: $4,677,820.00\n\n"
            "(b) To THOMAS JAMES WORTHINGTON, son, of 1200 Pacific Coast Highway, Malibu, "
            "CA 90265 — 40% of the net estate: $4,677,820.00\n\n"
            "(c) To THE UNIVERSITY OF CHICAGO, for the Margaret Worthington Memorial Scholarship "
            "Fund, 5801 South Ellis Avenue, Chicago, IL 60637 — 10% of the net estate: $1,169,455.00\n\n"
            "(d) To THE ART INSTITUTE OF CHICAGO, 111 South Michigan Avenue, Chicago, IL 60603 — "
            "5% of the net estate: $584,727.50\n\n"
            "(e) To CATHOLIC CHARITIES OF THE ARCHDIOCESE OF CHICAGO, 721 North LaSalle Drive, "
            "Chicago, IL 60654 — 5% of the net estate: $584,727.50\n\n"
            "V. ORDER\n\n"
            "IT IS HEREBY ORDERED that the Executor shall distribute the estate in accordance "
            "with the foregoing findings within sixty (60) days of the date of this Order. The "
            "Executor shall file a receipt of distribution with this Court upon completion.\n\n"
            "The claim filed by DAVID MICHAEL WORTHINGTON, nephew, of 445 East Ohio Street, "
            "Chicago, IL 60611, contesting the validity of the Will under 755 ILCS 5/4-1, is "
            "DENIED. The Court finds that the Decedent had testamentary capacity and was not "
            "subject to undue influence. See In re Estate of Hoover, 155 Ill. 2d 402 (1993); "
            "In re Estate of Henke, 203 Ill. App. 3d 975 (1990).\n\n"
            "ENTERED this 1st day of March, 2024.\n\n"
            "Hon. Patricia M. Sullivan\n"
            "Judge of the Circuit Court of Cook County\n"
            "Richard J. Daley Center\n"
            "50 West Washington Street\n"
            "Chicago, Illinois 60602"
        ),
    },
    "property-verbs": {
        "title": "Property Verbs",
        "description": "Appellate decision dense with granted/denied/reversed/remanded action verbs",
        "text": (
            "SUPREME COURT OF THE STATE OF NEW YORK\n"
            "APPELLATE DIVISION, FIRST DEPARTMENT\n\n"
            "People of the State of New York,\n"
            "  Respondent,\n\n"
            "v.\n\n"
            "CARLOS ANTONIO REYES,\n"
            "  Defendant-Appellant.\n\n"
            "Ind. No. 2023/01456\n"
            "Calendar No. 2024-00892\n\n"
            "DECISION AND ORDER\n\n"
            "Appeal from a judgment of the Supreme Court, New York County (Justice Patricia A. "
            "Williams), rendered October 15, 2023, convicting defendant, after a jury trial, of "
            "robbery in the first degree (Penal Law \u00A7 160.15), assault in the second degree "
            "(Penal Law \u00A7 120.05), and criminal possession of a weapon in the third degree "
            "(Penal Law \u00A7 265.02), and sentencing him to concurrent terms of 12 years, 5 years, "
            "and 7 years, respectively.\n\n"
            "The judgment is unanimously MODIFIED, on the law, to the extent of REDUCING the conviction "
            "of robbery in the first degree to robbery in the second degree, and otherwise AFFIRMED.\n\n"
            "I. BACKGROUND\n\n"
            "On the evening of March 3, 2023, at approximately 9:30 PM, the complainant, James "
            "Morrison, was walking near the intersection of Broadway and West 125th Street in "
            "Manhattan when defendant approached him and demanded his wallet. The complainant "
            "testified that defendant displayed what appeared to be a firearm, a silver-colored "
            "object that the complainant believed to be a handgun. The complainant surrendered "
            "his wallet containing $340.00, two credit cards issued by Citibank, N.A., and his "
            "New York State driver's license.\n\n"
            "Defendant was apprehended by NYPD Officers Rodriguez and Kim approximately four blocks "
            "from the scene. No firearm was recovered. A silver-colored cigarette lighter was found "
            "in defendant's pocket.\n\n"
            "II. ISSUES ON APPEAL\n\n"
            "Defendant raises the following claims: (1) the trial court erred in denying his motion "
            "to suppress identification testimony; (2) the evidence was legally insufficient to "
            "support the first-degree robbery conviction; (3) the sentence imposed was excessive; "
            "and (4) the court improperly admitted certain hearsay testimony.\n\n"
            "III. ANALYSIS\n\n"
            "A. Suppression Motion\n\n"
            "Defendant's motion to suppress the showup identification was properly DENIED. The "
            "identification procedure was conducted within 30 minutes of the crime and in close "
            "proximity to the scene. Under the totality of the circumstances, the procedure was "
            "not unduly suggestive. See People v. Duuvon, 77 N.Y.2d 541 (1991); Neil v. Biggers, "
            "409 U.S. 188 (1972). The motion court correctly determined that the identification "
            "was reliable under the factors set forth in Manson v. Brathwaite, 432 U.S. 98 (1977).\n\n"
            "B. Legal Sufficiency — First-Degree Robbery\n\n"
            "Robbery in the first degree requires proof that the defendant was armed with a deadly "
            "weapon or dangerous instrument. Penal Law \u00A7 160.15(2). A cigarette lighter, without "
            "more, does not constitute a dangerous instrument within the meaning of the statute. "
            "The People's argument that the lighter functioned as a \"display\" weapon is unavailing.\n\n"
            "However, the evidence was sufficient to sustain a conviction of robbery in the second "
            "degree (Penal Law \u00A7 160.10), which requires only that the defendant be aided by "
            "another person actually present, or that the defendant display what appears to be a "
            "weapon. The complainant's testimony established that defendant displayed an object "
            "that reasonably appeared to be a firearm, satisfying the statutory element.\n\n"
            "Accordingly, the first-degree robbery conviction is REDUCED to robbery in the second "
            "degree, and the matter is REMANDED for resentencing on that count.\n\n"
            "C. Sentence\n\n"
            "Defendant's request for a reduced sentence on the remaining counts is DENIED. The "
            "sentences of 5 years for assault in the second degree and 7 years for criminal "
            "possession of a weapon in the third degree were within the statutory range and were "
            "not excessive given defendant's prior criminal history, which includes two prior "
            "felony convictions.\n\n"
            "D. Hearsay Claim\n\n"
            "Defendant's claim that the trial court improperly admitted Officer Rodriguez's "
            "testimony regarding a radio transmission describing the suspect is REJECTED. The "
            "testimony was not admitted for its truth but to explain the officer's course of "
            "conduct. See People v. Tosca, 98 N.Y.2d 660 (2002). The motion to strike this "
            "testimony was properly DENIED.\n\n"
            "E. Additional Motions\n\n"
            "Defendant's motion for leave to appeal to the Court of Appeals is GRANTED. The "
            "People's cross-motion to dismiss the appeal as moot is DENIED. Defendant's "
            "application for assignment of appellate counsel is GRANTED, and the Legal Aid "
            "Society is appointed to represent defendant on further appeal.\n\n"
            "IV. DISPOSITION\n\n"
            "The judgment is MODIFIED, on the law, to the extent of reducing the conviction of "
            "robbery in the first degree to robbery in the second degree, and the matter is "
            "REMANDED to Supreme Court, New York County, for resentencing on that count. The "
            "judgment is otherwise AFFIRMED.\n\n"
            "ENTERED: March 8, 2024\n\n"
            "Presiding Justice David T. Acosta\n"
            "Associate Justice Maria L. Gonzalez\n"
            "Associate Justice Robert K. Chen\n"
            "Associate Justice Sophia N. Williams\n"
            "Associate Justice James P. O'Brien"
        ),
    },
    "synonyms": {
        "title": "Synonyms",
        "description": "Cross-jurisdictional terminology survey with DUI/DWI, AV/Self-Driving, and other variant terms",
        "text": (
            "CROSS-JURISDICTIONAL REGULATORY COMPLIANCE MEMORANDUM\n\n"
            "TO:        State Legislative Counsel Conference — Emerging Issues Committee\n"
            "FROM:      National Conference of Commissioners on Uniform State Laws\n"
            "DATE:      March 1, 2024\n"
            "RE:        Survey of Variant Terminology in State Criminal and Regulatory Codes\n\n"
            "I. INTRODUCTION\n\n"
            "This memorandum surveys how different states use different terminology for identical legal "
            "concepts, creating confusion for practitioners, courts, and regulated entities operating "
            "across state lines. The goal is to identify areas where uniform terminology would reduce "
            "compliance burdens and improve access to justice.\n\n"
            "II. IMPAIRED DRIVING LAWS\n\n"
            "Perhaps no area of criminal law better illustrates the terminology problem than impaired "
            "driving offenses. The same criminal conduct — operating a motor vehicle while impaired "
            "by alcohol or drugs — is known by different names across jurisdictions:\n\n"
            "- California, Florida, and 34 other states use \"Driving Under the Influence\" or "
            "\"DUI\" as the statutory offense.\n"
            "- Texas, New York, and New Jersey use \"Driving While Intoxicated\" or \"DWI\" as "
            "their primary charge.\n"
            "- Ohio uses \"Operating a Vehicle Under the Influence\" or \"OVI.\"\n"
            "- Several states distinguish between DUI (drugs) and DWI (alcohol), while others "
            "treat them as synonymous.\n\n"
            "When a driver with a DUI conviction in California applies for a commercial license "
            "in Texas, the Texas DWI database may not flag the California DUI conviction. Interstate "
            "compact reporting systems must map between DWI and DUI records.\n\n"
            "The Model Penal Code's proposed uniform terminology of \"Impaired Operation of a Vehicle\" "
            "has gained little traction, and practitioners continue to navigate the DUI/DWI patchwork.\n\n"
            "III. AUTONOMOUS VEHICLE REGULATION\n\n"
            "The rapid deployment of autonomous vehicle technology has outpaced legislative drafting. "
            "Each state uses different terminology:\n\n"
            "- California's Vehicle Code refers to an \"Autonomous Vehicle\" and requires a permit "
            "for testing on public roads.\n"
            "- The federal SELF DRIVE Act uses \"Self-Driving Vehicle\" and would preempt state "
            "design standards.\n"
            "- Arizona permits operation of a \"Driverless Car\" without a human safety operator.\n"
            "- The U.S. Department of Transportation uses \"Connected Vehicle\" to encompass both "
            "automated and vehicle-to-infrastructure communication systems.\n"
            "- Industry groups use \"CAV\" (Connected and Autonomous Vehicle) as a catch-all.\n\n"
            "The liability implications are significant. When a Self-Driving Vehicle manufactured in "
            "Michigan causes an accident in Arizona involving a Driverless Car operating under "
            "Arizona's testing program, which state's Autonomous Vehicle statute governs? Personal "
            "Injury and Tort Law has struggled to adapt.\n\n"
            "IV. FIREARMS PERMITTING\n\n"
            "Concealed carry permitting demonstrates another area of divergence:\n\n"
            "- Texas issues a \"Concealed Handgun License\" through the Department of Public Safety.\n"
            "- Florida issues a \"Concealed Weapons Permit\" through the Department of Agriculture.\n"
            "- Virginia issues a \"Concealed Carry Permit\" through the circuit courts.\n"
            "- Utah issues a \"Concealed Firearm Permit\" through the Bureau of Criminal "
            "Identification.\n\n"
            "A traveler holding a Concealed Weapons Permit from Florida may not realize that their "
            "permit is called a Concealed Firearm Permit in Utah's reciprocity database.\n\n"
            "V. DISABILITY ACCOMMODATIONS\n\n"
            "Federal and state laws use varying terminology for the same conditions:\n\n"
            "- The ADA uses \"Cognitive Impairment\" as a broad category.\n"
            "- State education codes refer to \"Intellectual Disability,\" replacing outdated "
            "terminology eliminated by Rosa's Law (Pub. L. 111-256).\n"
            "- State developmental services agencies use \"Developmental Disability\" as their "
            "eligibility trigger.\n"
            "- Some state civil rights statutes use \"Cognitive Disability\" as the protected "
            "category.\n\n"
            "VI. DOMESTIC VIOLENCE PROTECTIONS\n\n"
            "Protective order terminology varies significantly:\n\n"
            "- California issues a \"Domestic Violence Restraining Order\" under Family Code "
            "\u00A7 6300.\n"
            "- Ohio issues a \"Civil Protection Order\" under ORC \u00A7 2903.214.\n"
            "- The Violence Against Women Act (18 U.S.C. \u00A7 2265) requires states to enforce "
            "protective orders from other jurisdictions, but the terminological differences create "
            "confusion at the enforcement stage.\n\n"
            "VII. ELECTORAL REFORM\n\n"
            "Electoral systems terminology is particularly inconsistent:\n\n"
            "- Maine and Alaska have adopted \"Ranked-Choice Voting\" for federal elections.\n"
            "- Academic literature refers to the same system as \"Instant Runoff Voting\" or \"IRV.\"\n"
            "- The United Kingdom calls it the \"Alternative Vote\" system.\n"
            "- International organizations use \"Preferential Voting\" as the generic term.\n\n"
            "Whether called IRV, Sequential Runoff Voting, or Ranked-Choice Voting, the underlying "
            "mechanism is identical.\n\n"
            "VIII. RECOMMENDATIONS\n\n"
            "1. Establish a Uniform Legal Terminology Commission to harmonize state statutory language.\n"
            "2. Create a cross-reference database mapping equivalent terms across all 50 states.\n"
            "3. Adopt the Model Penal Code's terminology for criminal offenses.\n"
            "4. Require interstate compact reporting systems to include terminology mapping tables.\n\n"
            "Respectfully submitted,\n\n"
            "Office of the Executive Director\n"
            "National Conference of Commissioners on Uniform State Laws"
        ),
    },
    "kitchen-sink": {
        "title": "Kitchen Sink",
        "description": "Bankruptcy order exercising every pipeline feature: citations, entities, verbs, multi-branch, individuals",
        "text": (
            "UNITED STATES BANKRUPTCY COURT\n"
            "SOUTHERN DISTRICT OF NEW YORK\n\n"
            "In re:\n"
            "PACIFIC CONSOLIDATED HOLDINGS, INC.,\n"
            "  Debtor.\n\n"
            "Case No. 23-12345-ABC\n"
            "Chapter 11\n\n"
            "ORDER (I) APPROVING THE DISCLOSURE STATEMENT, (II) CONFIRMING THE DEBTOR'S "
            "FOURTH AMENDED PLAN OF REORGANIZATION, (III) AUTHORIZING THE SALE OF SUBSTANTIALLY "
            "ALL ASSETS, AND (IV) GRANTING RELATED RELIEF\n\n"
            "THIS MATTER came before the Court on the motion of Pacific Consolidated Holdings, "
            "Inc. (\"PCH\" or the \"Debtor\"), by and through its counsel, Sullivan & Cromwell LLP, "
            "125 Broad Street, New York, New York 10004, for entry of an order: (i) approving the "
            "Disclosure Statement for the Debtor's Fourth Amended Plan of Reorganization (the "
            "\"Plan\"); (ii) confirming the Plan pursuant to 11 U.S.C. \u00A7 1129; (iii) authorizing "
            "the sale of substantially all of the Debtor's assets to Blackstone Capital Partners "
            "IX L.P. (the \"Buyer\") pursuant to 11 U.S.C. \u00A7 363; and (iv) granting related "
            "relief.\n\n"
            "The Court having reviewed the Plan, the Disclosure Statement, the Plan Supplement, "
            "the Declaration of David R. Thornton, Chief Restructuring Officer (the \"CRO "
            "Declaration\"), the report of the Official Committee of Unsecured Creditors (the "
            "\"Committee\"), the objections filed by the Internal Revenue Service, the U.S. "
            "Trustee, and the ad hoc group of senior secured noteholders (the \"Ad Hoc Group\"), "
            "and having conducted an evidentiary hearing on February 15-16, 2024, at the United "
            "States Bankruptcy Court, One Bowling Green, New York, New York 10004, at which the "
            "following witnesses testified:\n\n"
            "1. David R. Thornton, Chief Restructuring Officer of PCH, 200 Park Avenue, New "
            "York, NY 10166\n"
            "2. Dr. Katherine M. Schwartz, Managing Director of Houlihan Lokey, Inc., financial "
            "advisor to the Debtor\n"
            "3. Gregory S. Park, Managing Director of Blackstone Group Inc.\n"
            "4. Professor Andrew J. Rosenberg, expert witness on valuation\n\n"
            "THE COURT HEREBY FINDS AND DETERMINES:\n\n"
            "I. JURISDICTION AND VENUE\n\n"
            "This Court has jurisdiction over this matter pursuant to 28 U.S.C. \u00A7\u00A7 157 "
            "and 1334. This is a core proceeding under 28 U.S.C. \u00A7 157(b)(2). Venue is "
            "proper in this district pursuant to 28 U.S.C. \u00A7 1408.\n\n"
            "II. BACKGROUND\n\n"
            "PCH filed its voluntary petition for relief under Chapter 11 of the Bankruptcy Code "
            "on September 1, 2023. PCH is a diversified holding company that, through its "
            "subsidiaries — including Pacific Energy Corp., Pacific Maritime LLC, Pacific Real "
            "Estate Advisors LLC, and Pacific Technology Ventures Inc. — operates in four "
            "business segments: energy, shipping, commercial real estate, and technology venture "
            "capital.\n\n"
            "As of the petition date, PCH's consolidated assets were valued at approximately "
            "$2,800,000,000.00 and its consolidated liabilities at approximately "
            "$3,400,000,000.00, representing a balance sheet insolvency of $600,000,000.00.\n\n"
            "The Debtor's capital structure includes:\n"
            "- Senior Secured Notes due 2025, issued pursuant to an Indenture dated March 15, "
            "2020, with U.S. Bank National Association as Indenture Trustee — $1,200,000,000.00\n"
            "- Term Loan B, with JPMorgan Chase Bank, N.A. as Administrative Agent — "
            "$800,000,000.00\n"
            "- Unsecured Notes due 2026, issued pursuant to an Indenture dated June 1, 2021, "
            "with The Bank of New York Mellon as Indenture Trustee — $500,000,000.00\n"
            "- General unsecured claims — approximately $400,000,000.00\n"
            "- Equity interests — no value\n\n"
            "III. DISCLOSURE STATEMENT APPROVAL\n\n"
            "The Disclosure Statement contains adequate information within the meaning of "
            "11 U.S.C. \u00A7 1125(a)(1). The Court finds that the Disclosure Statement provides "
            "creditors with sufficient information to make an informed judgment about the Plan, "
            "including a liquidation analysis prepared by Houlihan Lokey showing estimated "
            "recovery of 15-22 cents on the dollar in a Chapter 7 conversion.\n\n"
            "IV. PLAN CONFIRMATION\n\n"
            "The Plan satisfies all requirements of 11 U.S.C. \u00A7 1129(a) and (b):\n\n"
            "(a) Classification. The Plan classifies claims in accordance with \u00A7 1122. "
            "Class 1 (Administrative Claims), Class 2 (Priority Tax Claims), Class 3 (Senior "
            "Secured Claims), Class 4 (Term Loan Claims), Class 5 (Unsecured Note Claims), "
            "Class 6 (General Unsecured Claims), and Class 7 (Equity Interests).\n\n"
            "(b) Voting. Classes 3, 4, 5, and 6 voted to accept the Plan. Class 7 is deemed "
            "to reject. The Plan satisfies \u00A7 1129(a)(8) with respect to accepting classes "
            "and \u00A7 1129(b) (cramdown) with respect to Class 7.\n\n"
            "(c) Feasibility. Based on the testimony of Dr. Schwartz and the CRO Declaration, "
            "the Court finds that the Plan is feasible within the meaning of \u00A7 1129(a)(11).\n\n"
            "(d) Best Interests. All impaired creditors will receive at least as much under the "
            "Plan as they would in a Chapter 7 liquidation, satisfying \u00A7 1129(a)(7).\n\n"
            "Recovery under the Plan:\n"
            "- Class 3 (Senior Secured): 85 cents on the dollar — $1,020,000,000.00\n"
            "- Class 4 (Term Loan): 72 cents on the dollar — $576,000,000.00\n"
            "- Class 5 (Unsecured Notes): 35 cents on the dollar — $175,000,000.00\n"
            "- Class 6 (General Unsecured): 28 cents on the dollar — $112,000,000.00\n"
            "- Class 7 (Equity): 0%\n\n"
            "V. SALE AUTHORIZATION\n\n"
            "The sale of substantially all of the Debtor's assets to Blackstone Capital Partners "
            "IX L.P. for a purchase price of $1,950,000,000.00 is APPROVED pursuant to 11 U.S.C. "
            "\u00A7 363(b) and (f). The Court finds that the sale process was conducted in good "
            "faith and that Blackstone is a good faith purchaser entitled to the protections of "
            "\u00A7 363(m). See In re Abbotts Dairies of Pennsylvania, Inc., 788 F.2d 143 (3d "
            "Cir. 1986); In re Lionel Corp., 722 F.2d 1063 (2d Cir. 1983).\n\n"
            "VI. ADDITIONAL PROVISIONS\n\n"
            "1. All executory contracts not assumed by the effective date are REJECTED pursuant "
            "to 11 U.S.C. \u00A7 365.\n"
            "2. The employment agreement between PCH and David R. Thornton, providing for a "
            "success fee of $2,500,000.00, is APPROVED pursuant to \u00A7 327 and \u00A7 328.\n"
            "3. The Key Employee Incentive Plan (\"KEIP\") providing retention payments totaling "
            "$4,800,000.00 to 23 key employees is APPROVED pursuant to \u00A7 503(c).\n"
            "4. The IRS's claim for $45,000,000.00 in unpaid employment taxes is ALLOWED as a "
            "priority claim under \u00A7 507(a)(8).\n"
            "5. The U.S. Trustee's objection based on alleged plan funding deficiencies is "
            "OVERRULED.\n"
            "6. The Ad Hoc Group's objection to the proposed cramdown interest rate is DENIED.\n\n"
            "VII. EFFECTIVE DATE\n\n"
            "The effective date of the Plan shall be April 1, 2024, or the first business day "
            "after all conditions precedent in Article IX of the Plan are satisfied or waived.\n\n"
            "IT IS SO ORDERED.\n\n"
            "Dated: March 1, 2024\n"
            "New York, New York\n\n"
            "Hon. Robert D. Drain\n"
            "United States Bankruptcy Judge"
        ),
    },
}
