"""Slim baked demo JSON files by dropping data the frontend can re-hydrate by IRI.

Each demo file is ``{demo, cache}`` where ``cache.job.result`` holds the completed
job. Two families of data dominate the on-disk size and are *not needed inline*:

1. Per-stage concept dumps in ``result.metadata`` (``resolved_concepts``,
   ``ruler_concepts``, ``reconciled_concepts``, ``llm_concepts``). These are only
   consumed *during* the pipeline; a re-seeded demo job is already ``completed`` and
   never re-runs those stages. The frontend reads only ``.length`` of
   ``resolved_concepts``/``ruler_concepts`` (two integer counts), and no exporter reads
   any of them. So we DROP ``reconciled_concepts`` entirely and, for the length-only
   pair, KEEP the array (preserving ``.length``) but strip each entry's heavy
   descriptive payload. ``llm_concepts`` is KEPT: replay_fix_demos re-feeds it to
   reconcile deterministically (no Gemini re-run); it is tiny (~80 KB/file).

2. Heavy ``folio_*`` descriptive fields on each annotation candidate. The detail panel
   already hydrates these by IRI (``/concepts/{iri_hash}``); tooltips will follow. BUT
   several backend exporters (json, jsonld, html, csv, excel) read a subset of these
   *off annotation candidates*, and demo jobs are re-seeded so their exports must keep
   working. We therefore strip only the heavy fields NO exporter reads, and PROTECT the
   exporter-read subset on annotations.

The same ``slim_demo_cache`` is applied at bake time (generate_demos / replay_fix_demos)
so future bakes are born slim. The transform is idempotent.

Usage::

    cd backend && .venv/bin/python -m scripts.slim_demos          # slim in place
    cd backend && .venv/bin/python -m scripts.slim_demos --check   # report only, no write
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
DEMOS_DIR = BACKEND_ROOT.parent / "frontend" / "demos"

# Heavy descriptive fields carried on every concept candidate. All are re-hydratable by
# IRI via /concepts/{iri_hash} + /concepts/batch, so none need to live inline.
_HEAVY_CANDIDATE_FIELDS = frozenset(
    {
        "folio_definition",
        "folio_examples",
        "folio_notes",
        "folio_see_also",
        "folio_source",
        "folio_alt_labels",
        "folio_editorial_note",
        "folio_comment",
        "folio_description",
        "folio_history_note",
        "folio_country",
        "folio_deprecated",
        "folio_hidden_label",
        "translations",
        "hierarchy_path",
    }
)

# Fields that backend EXPORTERS read off *annotation* candidates. Stripping these from
# annotations would change demo-job export output, so they are protected on annotations.
#   json_exporter / jsonld_exporter: folio_definition, folio_examples, folio_alt_labels,
#                                     folio_see_also, folio_source
#   html_exporter:                   folio_definition
#   csv_exporter / excel_exporter:   folio_definition, hierarchy_path
_EXPORTER_PROTECTED = frozenset(
    {
        "folio_definition",
        "folio_examples",
        "folio_alt_labels",
        "folio_see_also",
        "folio_source",
        "hierarchy_path",
    }
)

# Metadata concept-dump keys with NO post-completion consumer (frontend or exporter)
# AND not needed to re-bake. reconciled_concepts is regenerated by replay_fix_demos
# (it re-runs Reconciliation), so it's safe to drop. NOTE: llm_concepts is deliberately
# NOT dropped — replay_fix_demos re-feeds preserved metadata.llm_concepts to reconcile
# deterministically without re-running Gemini (see project_demo_replay_rebake). It's
# only ~80 KB/file, so keeping it costs almost nothing and preserves the replay path.
_DROP_META_KEYS = ("reconciled_concepts",)

# Metadata concept-dump keys whose ARRAY LENGTH the frontend renders (EntityRuler /
# Resolved Concepts counts). Keep the list (length preserved); slim each entry.
_LENGTH_ONLY_META_KEYS = ("resolved_concepts", "ruler_concepts")

# Internal per-entry keys inside the metadata dumps; dead weight post-completion.
_META_ENTRY_INTERNAL = ("_backup_candidates", "_lineage_events")


def _strip_candidate(candidate: dict, protect: frozenset[str]) -> None:
    """Drop heavy fields from a single concept candidate, keeping ``protect``."""
    if not isinstance(candidate, dict):
        return
    for field in _HEAVY_CANDIDATE_FIELDS:
        if field not in protect:
            candidate.pop(field, None)


def slim_demo_cache(doc: dict) -> dict:
    """Slim a demo document in place and return it.

    Accepts either the whole ``{demo, cache}`` document or a bare ``cache`` dict
    (anything with a ``job`` key). Idempotent: safe to run repeatedly.
    """
    if not isinstance(doc, dict):
        return doc
    cache = doc.get("cache") if isinstance(doc.get("cache"), dict) else doc
    result = (((cache or {}).get("job") or {}).get("result")) or {}
    if not isinstance(result, dict):
        return doc

    # --- metadata per-stage concept dumps ---
    metadata = result.get("metadata")
    if isinstance(metadata, dict):
        for key in _DROP_META_KEYS:
            metadata.pop(key, None)
        for key in _LENGTH_ONLY_META_KEYS:
            entries = metadata.get(key)
            if isinstance(entries, list):
                for entry in entries:
                    # No exporter/frontend reads these entries' contents (only length),
                    # so strip ALL heavy fields plus internal bookkeeping.
                    _strip_candidate(entry, protect=frozenset())
                    if isinstance(entry, dict):
                        for internal in _META_ENTRY_INTERNAL:
                            entry.pop(internal, None)

    # --- annotation candidates (+ any backup candidates) ---
    for annotation in result.get("annotations") or []:
        if not isinstance(annotation, dict):
            continue
        for candidate in annotation.get("concepts") or []:
            _strip_candidate(candidate, protect=_EXPORTER_PROTECTED)
        for candidate in annotation.get("_backup_candidates") or []:
            _strip_candidate(candidate, protect=_EXPORTER_PROTECTED)

    return doc


def _dumps(doc: dict) -> str:
    return json.dumps(doc, separators=(",", ":"), ensure_ascii=False)


def main(argv: list[str]) -> int:
    check_only = "--check" in argv
    if not DEMOS_DIR.is_dir():
        print(f"demos dir not found: {DEMOS_DIR}")
        return 1

    files = sorted(DEMOS_DIR.glob("*.json"))
    if not files:
        print(f"no demo files in {DEMOS_DIR}")
        return 1

    total_before = 0
    total_after = 0
    for path in files:
        original = path.read_text(encoding="utf-8")
        before = len(original.encode("utf-8"))
        doc = json.loads(original)
        slimmed = _dumps(slim_demo_cache(doc))
        after = len(slimmed.encode("utf-8"))
        total_before += before
        total_after += after
        pct = (1 - after / before) * 100 if before else 0.0
        action = "would slim" if check_only else "slimmed"
        print(f"  {path.name:28} {before/1e6:6.2f} MB -> {after/1e6:6.2f} MB  (-{pct:4.1f}%)  {action}")
        if not check_only:
            path.write_text(slimmed, encoding="utf-8")

    pct = (1 - total_after / total_before) * 100 if total_before else 0.0
    print(
        f"\nTOTAL {total_before/1e6:.2f} MB -> {total_after/1e6:.2f} MB "
        f"(-{pct:.1f}%, saved {(total_before-total_after)/1e6:.2f} MB across {len(files)} files)"
    )
    if check_only:
        print("(--check: no files written)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
