"""Tests for the demo-slim transform (scripts/slim_demos.slim_demo_cache).

Guards the size/fidelity contract: drop only data with no post-completion consumer,
keep everything exporters/tooltips read off annotations, and keep llm_concepts (the
deterministic-replay input).
"""

from __future__ import annotations

import copy

from scripts.slim_demos import slim_demo_cache


def _doc() -> dict:
    """A minimal demo doc exercising every slim branch."""
    candidate = {
        # light identity/scoring fields — MUST survive
        "concept_text": "limited liability company",
        "folio_iri": "https://folio.openlegalstandard.org/R123",
        "folio_label": "Limited Liability Company",
        "iri_hash": "R123",
        "confidence": 0.9,
        "state": "confirmed",
        "branches": ["Legal Entity"],
        "branch_color": "#abc",
        "source": "llm",
        # exporter/tooltip-read folio_* — MUST survive (protected)
        "folio_definition": "An LLC is ...",
        "folio_examples": ["ex1"],
        "folio_alt_labels": ["LLC"],
        "folio_see_also": ["R999"],
        "folio_source": "src",
        "hierarchy_path": ["Thing", "Legal Entity"],
        # heavy, no consumer — MUST be stripped
        "folio_notes": "n" * 500,
        "folio_editorial_note": "e" * 500,
        "folio_comment": "c" * 500,
        "folio_description": "d" * 500,
        "folio_history_note": "h" * 500,
        "folio_country": "US",
        "folio_deprecated": False,
        "translations": {"fr": "SARL"},
    }
    return {
        "demo": {"slug": "x"},
        "cache": {
            "job": {
                "result": {
                    "annotations": [{"concepts": [copy.deepcopy(candidate)]}],
                    "properties": [{"folio_definition": "keep me", "property_text": "p"}],
                    "metadata": {
                        "resolved_concepts": [dict(candidate)],
                        "ruler_concepts": [dict(candidate)],
                        "reconciled_concepts": [dict(candidate)],
                        "llm_concepts": {"0": [{"concept_text": "x"}]},
                    },
                }
            }
        },
    }


def _candidate(doc: dict) -> dict:
    return doc["cache"]["job"]["result"]["annotations"][0]["concepts"][0]


class TestSlimDemoCache:
    def test_drops_reconciled_but_keeps_llm_concepts(self):
        meta = slim_demo_cache(_doc())["cache"]["job"]["result"]["metadata"]
        assert "reconciled_concepts" not in meta          # regenerated by replay
        assert "llm_concepts" in meta                      # replay input — must stay
        assert meta["llm_concepts"] == {"0": [{"concept_text": "x"}]}

    def test_length_only_arrays_kept_but_entries_slimmed(self):
        meta = slim_demo_cache(_doc())["cache"]["job"]["result"]["metadata"]
        # arrays kept (frontend reads .length) ...
        assert len(meta["resolved_concepts"]) == 1
        assert len(meta["ruler_concepts"]) == 1
        # ... but their heavy entry payload is gone
        assert "folio_definition" not in meta["resolved_concepts"][0]
        assert "folio_notes" not in meta["ruler_concepts"][0]

    def test_keeps_light_and_exporter_protected_fields_on_annotations(self):
        c = _candidate(slim_demo_cache(_doc()))
        for keep in (
            "folio_iri", "iri_hash", "confidence", "state", "branches",
            "folio_definition", "folio_examples", "folio_alt_labels",
            "folio_see_also", "folio_source", "hierarchy_path",
        ):
            assert keep in c, f"{keep} must survive slimming"

    def test_strips_unconsumed_heavy_fields_on_annotations(self):
        c = _candidate(slim_demo_cache(_doc()))
        for drop in (
            "folio_notes", "folio_editorial_note", "folio_comment",
            "folio_description", "folio_history_note", "folio_country",
            "folio_deprecated", "translations",
        ):
            assert drop not in c, f"{drop} should have been stripped"

    def test_properties_untouched(self):
        props = slim_demo_cache(_doc())["cache"]["job"]["result"]["properties"]
        assert props[0]["folio_definition"] == "keep me"

    def test_idempotent(self):
        once = slim_demo_cache(_doc())
        twice = slim_demo_cache(copy.deepcopy(once))
        assert once == twice
