"""Shared POS lookup utility.

Maps character spans to POS tags using sentence_pos data generated by
EarlyTripleStage (spaCy dependency parsing).
"""

from __future__ import annotations

from collections import Counter


def get_pos_for_span(
    char_start: int, char_end: int, sentence_pos_list: list[dict]
) -> list[str]:
    """Return universal POS tags for tokens overlapping [char_start, char_end).

    Finds the sentence containing the span, reconstructs per-token character
    offsets by walking sentence text with cursor advancement, and returns POS
    tags for overlapping tokens.
    """
    if not sentence_pos_list:
        return []

    # Find sentence(s) containing the span
    for sent in sentence_pos_list:
        sent_start = sent.get("start", 0)
        sent_end = sent.get("end", 0)
        # Span must overlap with sentence
        if char_start >= sent_end or char_end <= sent_start:
            continue

        tokens = sent.get("tokens", [])
        pos_tags = sent.get("pos_tags", [])
        sent_text = sent.get("text", "")

        if not tokens or len(tokens) != len(pos_tags):
            continue

        # Reconstruct per-token absolute character offsets
        result: list[str] = []
        cursor = 0
        for tok, pos in zip(tokens, pos_tags):
            idx = sent_text.find(tok, cursor)
            if idx == -1:
                continue
            tok_abs_start = sent_start + idx
            tok_abs_end = tok_abs_start + len(tok)
            cursor = idx + len(tok)

            # Check overlap with target span
            if tok_abs_start < char_end and tok_abs_end > char_start:
                result.append(pos)

        if result:
            return result

    return []


def get_majority_pos(
    char_start: int, char_end: int, sentence_pos_list: list[dict]
) -> str | None:
    """Return the most frequent POS tag in the span, or None if no data."""
    tags = get_pos_for_span(char_start, char_end, sentence_pos_list)
    if not tags:
        return None
    return Counter(tags).most_common(1)[0][0]


def get_fine_tags_for_span(
    char_start: int, char_end: int, sentence_pos_list: list[dict]
) -> list[str]:
    """Return Penn Treebank fine tags for tokens overlapping the span."""
    if not sentence_pos_list:
        return []

    for sent in sentence_pos_list:
        sent_start = sent.get("start", 0)
        sent_end = sent.get("end", 0)
        if char_start >= sent_end or char_end <= sent_start:
            continue

        tokens = sent.get("tokens", [])
        fine_tags = sent.get("fine_tags", [])
        sent_text = sent.get("text", "")

        if not tokens or len(tokens) != len(fine_tags):
            continue

        result: list[str] = []
        cursor = 0
        for tok, tag in zip(tokens, fine_tags):
            idx = sent_text.find(tok, cursor)
            if idx == -1:
                continue
            tok_abs_start = sent_start + idx
            tok_abs_end = tok_abs_start + len(tok)
            cursor = idx + len(tok)

            if tok_abs_start < char_end and tok_abs_end > char_start:
                result.append(tag)

        if result:
            return result

    return []
